# NixOS system configuration for these dotfiles.
#
# `dotfile packages` symlinks this file to /etc/nixos/configuration.nix and runs
# `nixos-rebuild switch`. Per-machine values (username, hostname, timezone,
# stateVersion) are auto-detected on first run and written to
# /etc/nixos/machine.nix — edit that file (not this one) to change them.
#
# hardware-configuration.nix is machine-generated by the NixOS installer and is
# used in place from /etc/nixos; it is not tracked in this repo.
{ config, pkgs, lib, ... }:

let
  machine = import /etc/nixos/machine.nix;
in
{
  imports = [
    /etc/nixos/hardware-configuration.nix
  ];

  # --- System core ---------------------------------------------------------
  system.stateVersion = machine.stateVersion;
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  nixpkgs.config.allowUnfree = true;   # google-chrome, etc.
  # Keep /nix/store bounded: dedup identical files and prune old generations.
  nix.settings.auto-optimise-store = true;
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 30d";
  };
  time.timeZone = machine.timeZone;
  i18n.defaultLocale = "en_US.UTF-8";
  networking.hostName = machine.hostName;
  networking.networkmanager.enable = true;
  networking.firewall.allowedTCPPorts = [ 22 ];

  services.openssh = {
    enable = true;
    openFirewall = true;
    settings = {
      PermitRootLogin = "no";
    };
  };

  # --- Boot ----------------------------------------------------------------
  boot.loader.systemd-boot.enable = true;     # EDIT: use GRUB instead if needed
  boot.loader.systemd-boot.configurationLimit = 10;  # cap boot menu / ESP usage
  boot.loader.efi.canTouchEfiVariables = true;

  # --- User ----------------------------------------------------------------
  programs.zsh.enable = true;
  programs.gnupg.agent = {
    enable = true;
    pinentryPackage = pkgs.pinentry-curses;
  };
  users.users.${machine.username} = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
    shell = pkgs.zsh;
  };

  # --- Desktop: Hyprland + greetd login ------------------------------------
  hardware.graphics.enable = true;   # GPU accel; EDIT: add vendor driver (e.g. nvidia)
  programs.hyprland.enable = true;

  # Audio (PipeWire) and screenshare/file-picker portals — hardware-independent.
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    pulse.enable = true;
  };
  xdg.portal = {
    enable = true;
    extraPortals = [ pkgs.xdg-desktop-portal-hyprland ];
  };

  services.greetd = {
    enable = true;
    settings.default_session = {
      command = "${pkgs.tuigreet}/bin/tuigreet --time --cmd Hyprland";
      user = "greeter";
    };
  };

  # --- Input method: fcitx5 ------------------------------------------------
  i18n.inputMethod = {
    enable = true;
    type = "fcitx5";
    fcitx5.addons = with pkgs; [ qt6Packages.fcitx5-unikey ];   # EDIT: your input addons
  };

  # --- Fonts ---------------------------------------------------------------
  fonts.packages = with pkgs; [ nerd-fonts.fira-code ];

  # --- Packages ------------------------------------------------------------
  # Ported from ARCH_PACKAGES in scripts/packages.sh. App config files stay as
  # symlinked dotfiles (dotfile symlinks); NixOS only installs the binaries.
  # ghostty/opencode/codex are appended only if the running channel provides
  # them, so this evaluates cleanly on stable channels that predate them.
  environment.systemPackages =
    (with pkgs; [
      git
      jq
      zsh
      tmux
      neovim
      gcc
      fzf
      fd
      ripgrep
      lazygit
      jujutsu
      starship
      zoxide
      gnupg
      wl-clipboard
      openssh
      unzip
      fontconfig
      tree-sitter
      nodejs
      lua5_1
      luarocks
      waybar
      google-chrome    # Mod+B keybind + OAuth sign-in (opencode/codex)
    ])
    ++ lib.optional (pkgs ? ghostty) pkgs.ghostty
    ++ lib.optional (pkgs ? opencode) pkgs.opencode
    ++ lib.optional (pkgs ? codex) pkgs.codex;
}
