# NixOS system configuration for these dotfiles.
#
# `dotfile packages` rebuilds the repo flake. Per-machine values (username,
# hostname, timezone, stateVersion) live in ../host.nix.
#
# hardware-configuration.nix is machine-generated by the NixOS installer and
# tracked for this host so flake evaluation stays pure.
{ config, pkgs, ... }:

let
  machine = import ../host.nix;
in
{
  imports = [
    ../hardware-configuration.nix
  ];

  # --- System core ---------------------------------------------------------
  system.stateVersion = machine.stateVersion;
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  nixpkgs.config.allowUnfree = true;   # Home Manager uses google-chrome.
  # Keep /nix/store bounded: dedup identical files and prune old generations.
  nix.settings.auto-optimise-store = true;
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 30d";
  };
  time.timeZone = machine.timeZone;
  i18n.defaultLocale = "en_US.UTF-8";
  console = {
    font = "ter-v32n";
    packages = [ pkgs.terminus_font ];
  };
  networking.hostName = machine.hostName;
  networking.networkmanager.enable = true;

  services.openssh = {
    enable = true;
    openFirewall = true;
    settings = {
      PermitRootLogin = "no";
    };
  };

  # --- Boot ----------------------------------------------------------------
  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.configurationLimit = 10;  # cap boot menu / ESP usage
  boot.loader.efi.canTouchEfiVariables = true;

  # --- User ----------------------------------------------------------------
  programs.zsh.enable = true;
  services.gnome.gnome-keyring.enable = true;
  security.sudo.extraConfig = ''
    Defaults timestamp_timeout=30
  '';
  programs.gnupg.agent = {
    enable = true;
    pinentryPackage = pkgs.pinentry-gnome3;
    settings = {
      default-cache-ttl = 28800; # 8 hours
      max-cache-ttl = 86400;     # 24 hours
    };
  };
  users.users.${machine.username} = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
    shell = pkgs.zsh;
  };

  home-manager.useGlobalPkgs = true;
  home-manager.useUserPackages = true;
  home-manager.users.${machine.username} = import ../home.nix;

  # --- Desktop: Hyprland + greetd login ------------------------------------
  hardware.graphics.enable = true;
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = true;
    open = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  programs.hyprland = {
    enable = true;
    withUWSM = true;
  };
  security.pam.services.hyprlock = { };

  programs.thunar = {
    enable = true;
    plugins = with pkgs; [ thunar-archive-plugin thunar-volman ];
  };
  services.gvfs.enable = true;
  services.tumbler.enable = true;
  services.udisks2.enable = true;
  environment.systemPackages = [ pkgs.xarchiver ];
  environment.etc."opt/chrome/policies/managed/dotfiles.json".text =
    builtins.toJSON { BackgroundModeEnabled = false; };

  # Audio (PipeWire) and screenshare/file-picker portals — hardware-independent.
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    pulse.enable = true;
  };
  xdg.portal = {
    enable = true;
    extraPortals = [ pkgs.xdg-desktop-portal-hyprland ];
  };

  services.greetd = {
    enable = true;
    settings.default_session = {
      command = "${pkgs.tuigreet}/bin/tuigreet --time --remember --asterisks --width 60 --cmd '${pkgs.uwsm}/bin/uwsm start -e -D Hyprland hyprland.desktop'";
      user = "greeter";
    };
  };

  # --- Input method: fcitx5 ------------------------------------------------
  i18n.inputMethod = {
    enable = true;
    type = "fcitx5";
    fcitx5.addons = with pkgs; [
      qt6Packages.fcitx5-chinese-addons
      qt6Packages.fcitx5-unikey
    ];
  };

  # --- Fonts ---------------------------------------------------------------
  fonts.packages = with pkgs; [ nerd-fonts.fira-code ];

}
