# NixOS system configuration for these dotfiles.
#
# `dotfile packages` rebuilds the repo flake. Per-machine values (username,
# hostname, timezone, stateVersion) live in ../host.nix.
#
# hardware-configuration.nix is machine-generated by the NixOS installer and
# tracked for this host so flake evaluation stays pure.
{ pkgs, ... }:

let
  machine = import ../host.nix;
in
{
  imports = [
    ../hardware-configuration.nix
  ];

  # --- System core ---------------------------------------------------------
  system.stateVersion = machine.stateVersion;
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  nixpkgs.config.allowUnfree = true;   # google-chrome, etc.
  # Keep /nix/store bounded: dedup identical files and prune old generations.
  nix.settings.auto-optimise-store = true;
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 30d";
  };
  time.timeZone = machine.timeZone;
  i18n.defaultLocale = "en_US.UTF-8";
  networking.hostName = machine.hostName;
  networking.networkmanager.enable = true;
  networking.firewall.allowedTCPPorts = [ 22 ];

  services.openssh = {
    enable = true;
    openFirewall = true;
    settings = {
      PermitRootLogin = "no";
    };
  };

  # --- Boot ----------------------------------------------------------------
  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.configurationLimit = 10;  # cap boot menu / ESP usage
  boot.loader.efi.canTouchEfiVariables = true;

  # --- User ----------------------------------------------------------------
  programs.zsh.enable = true;
  programs.gnupg.agent = {
    enable = true;
    pinentryPackage = pkgs.pinentry-gnome3;
    settings = {
      default-cache-ttl = 28800; # 8 hours
      max-cache-ttl = 86400;     # 24 hours
    };
  };
  users.users.${machine.username} = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
    shell = pkgs.zsh;
  };

  home-manager.useGlobalPkgs = true;
  home-manager.useUserPackages = true;
  home-manager.users.${machine.username} = import ../home.nix;

  # --- Desktop: Hyprland + greetd login ------------------------------------
  hardware.graphics.enable = true;
  programs.hyprland.enable = true;

  # Audio (PipeWire) and screenshare/file-picker portals — hardware-independent.
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    pulse.enable = true;
  };
  xdg.portal = {
    enable = true;
    extraPortals = [ pkgs.xdg-desktop-portal-hyprland ];
  };

  services.greetd = {
    enable = true;
    settings.default_session = {
      command = "${pkgs.tuigreet}/bin/tuigreet --time --cmd start-hyprland";
      user = "greeter";
    };
  };

  # --- Input method: fcitx5 ------------------------------------------------
  i18n.inputMethod = {
    enable = true;
    type = "fcitx5";
    fcitx5.addons = with pkgs; [ qt6Packages.fcitx5-unikey ];
  };

  # --- Fonts ---------------------------------------------------------------
  fonts.packages = with pkgs; [ nerd-fonts.fira-code ];

}
