#!/usr/bin/env bash
set -eo pipefail

OBSIDIAN_CONFIG_DEFAULT_VAULT="$HOME/documents/Sync/.obsidian"
OBSIDIAN_CONFIG_VAULT="${OBSIDIAN_CONFIG_VAULT:-$OBSIDIAN_CONFIG_DEFAULT_VAULT}"
OBSIDIAN_CONFIG_DEFAULT_SOURCE="$DOTFILES_DIR/config/shared/obsidian"
OBSIDIAN_CONFIG_SOURCE="${OBSIDIAN_CONFIG_SOURCE:-$OBSIDIAN_CONFIG_DEFAULT_SOURCE}"
